Repository BitcreditProtocol/Bitcredit-Core, pull requests merged in 2024-11, with the labels that each got.

#212 Update github actions to new versions.
  .github/workflows/rust.yml
  .github/workflows/test.yml
Labels: devops, improvment

#210 Notifications Part 1
  Cargo.lock
  Cargo.toml
  src/service/mod.rs
  src/service/notification_service/email.rs
  src/service/notification_service/email_lettre.rs
  src/service/notification_service/email_sendgrid.rs
  src/service/notification_service/event.rs
  src/service/notification_service/handler.rs
  src/service/notification_service/mod.rs
  src/service/notification_service/test_utils.rs
  src/service/notification_service/transport.rs
Labels: enhancement

#219 Rename CI actions. Add rust check formatting.
  .github/workflows/rust.yml
  .github/workflows/test.yml
Labels: devops, improvment

#230 Update README.md
  README.md
Labels: documentation
