Repository BitcreditProtocol/Bitcredit-Core, pull requests merged in 2025-03, with the labels that each got.

#435 Chain events part 1
  Cargo.toml
  crates/bcr-ebill-api/Cargo.toml
  crates/bcr-ebill-api/src/service/bill_service/error.rs
  crates/bcr-ebill-api/src/service/bill_service/issue.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/bill_service/test_utils.rs
  crates/bcr-ebill-api/src/service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/nostr.rs
  crates/bcr-ebill-api/src/service/notification_service/test_utils.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-core/src/blockchain/bill/chain.rs
  crates/bcr-ebill-core/src/notification.rs
  crates/bcr-ebill-persistence/src/db/mod.rs
  crates/bcr-ebill-persistence/src/db/nostr_send_queue.rs
  crates/bcr-ebill-persistence/src/nostr.rs
  crates/bcr-ebill-transport/Cargo.toml
  crates/bcr-ebill-transport/src/email/email_sendgrid.rs
  crates/bcr-ebill-transport/src/email/mod.rs
  crates/bcr-ebill-transport/src/event/bill_events.rs
  crates/bcr-ebill-transport/src/event/chain_event.rs
  crates/bcr-ebill-transport/src/event/mod.rs
  crates/bcr-ebill-transport/src/handler/bill_action_event_handler.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
  crates/bcr-ebill-transport/src/lib.rs
  crates/bcr-ebill-transport/src/notification_service.rs
  crates/bcr-ebill-transport/src/push_notification.rs
  crates/bcr-ebill-transport/src/transport.rs
  crates/bcr-ebill-web/Cargo.toml
  crates/bcr-ebill-web/src/error.rs
  crates/bcr-ebill-web/src/main.rs
Labels: Review effort 4/5

#444 Chain event handler
  crates/bcr-ebill-api/src/service/bill_service/issue.rs
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/payment.rs
  crates/bcr-ebill-api/src/service/bill_service/propagation.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/bill_service/test_utils.rs
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/nostr.rs
  crates/bcr-ebill-api/src/service/notification_service/test_utils.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-core/src/notification.rs
  crates/bcr-ebill-transport/src/event/bill_events.rs
  crates/bcr-ebill-transport/src/event/chain_event.rs
  crates/bcr-ebill-transport/src/event/mod.rs
  crates/bcr-ebill-transport/src/handler/bill_action_event_handler.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_handler.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
  crates/bcr-ebill-transport/src/lib.rs
  crates/bcr-ebill-transport/src/notification_service.rs
  crates/bcr-ebill-wasm/Cargo.toml
  crates/bcr-ebill-wasm/src/api/notification.rs
  crates/bcr-ebill-wasm/src/context.rs
  crates/bcr-ebill-web/src/service_context.rs
Labels: Review effort 4/5

#448 Failed message retry
  crates/bcr-ebill-api/src/persistence/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/test_utils.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-transport/src/notification_service.rs
  crates/bcr-ebill-wasm/src/context.rs
  crates/bcr-ebill-wasm/src/job.rs
  crates/bcr-ebill-web/src/service_context.rs
Labels: Review effort 3/5

#451 446 switch identity persistent & fix indexeddb problems
  CHANGELOG.md
  crates/bcr-ebill-api/src/external/time.rs
  crates/bcr-ebill-api/src/service/identity_service.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-core/src/identity.rs
  crates/bcr-ebill-core/src/util/mod.rs
  crates/bcr-ebill-persistence/Cargo.toml
  crates/bcr-ebill-persistence/src/constants.rs
  crates/bcr-ebill-persistence/src/db/backup.rs
  crates/bcr-ebill-persistence/src/db/bill.rs
  crates/bcr-ebill-persistence/src/db/bill_chain.rs
  crates/bcr-ebill-persistence/src/db/company.rs
  crates/bcr-ebill-persistence/src/db/company_chain.rs
  crates/bcr-ebill-persistence/src/db/contact.rs
  crates/bcr-ebill-persistence/src/db/file_upload.rs
  crates/bcr-ebill-persistence/src/db/identity.rs
  crates/bcr-ebill-persistence/src/db/identity_chain.rs
  crates/bcr-ebill-persistence/src/db/mod.rs
  crates/bcr-ebill-persistence/src/db/nostr_event_offset.rs
  crates/bcr-ebill-persistence/src/db/nostr_send_queue.rs
  crates/bcr-ebill-persistence/src/db/notification.rs
  crates/bcr-ebill-persistence/src/identity.rs
  crates/bcr-ebill-persistence/src/lib.rs
  crates/bcr-ebill-wasm/Cargo.toml
  crates/bcr-ebill-wasm/main.js
  crates/bcr-ebill-wasm/src/api/bill.rs
  crates/bcr-ebill-wasm/src/api/general.rs
  crates/bcr-ebill-wasm/src/api/identity.rs
  crates/bcr-ebill-wasm/src/constants.rs
  crates/bcr-ebill-wasm/src/context.rs
  crates/bcr-ebill-wasm/src/lib.rs
  crates/bcr-ebill-web/Cargo.toml
Labels: Review effort 4/5

#453 Fix Test Coverage Github Action
  .github/workflows/test.yml
Labels: Review effort 1/5

#454 Expose errors to TS, add Debug logging and some refactoring
  CHANGELOG.md
  crates/bcr-ebill-api/Cargo.toml
  crates/bcr-ebill-api/src/data/mod.rs
  crates/bcr-ebill-api/src/external/bitcoin.rs
  crates/bcr-ebill-api/src/service/bill_service/issue.rs
  crates/bcr-ebill-api/src/service/bill_service/payment.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/company_service.rs
  crates/bcr-ebill-api/src/service/contact_service.rs
  crates/bcr-ebill-api/src/service/file_upload_service.rs
  crates/bcr-ebill-api/src/service/identity_service.rs
  crates/bcr-ebill-api/src/service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-api/src/service/search_service.rs
  crates/bcr-ebill-core/Cargo.toml
  crates/bcr-ebill-core/src/lib.rs
  crates/bcr-ebill-persistence/Cargo.toml
  crates/bcr-ebill-persistence/src/constants.rs
  crates/bcr-ebill-persistence/src/db/file_upload.rs
  crates/bcr-ebill-transport/Cargo.toml
  crates/bcr-ebill-transport/src/handler/bill_chain_event_handler.rs
  crates/bcr-ebill-wasm/Cargo.toml
  crates/bcr-ebill-wasm/src/api/bill.rs
  crates/bcr-ebill-wasm/src/api/company.rs
  crates/bcr-ebill-wasm/src/api/contact.rs
  crates/bcr-ebill-wasm/src/api/identity.rs
  crates/bcr-ebill-wasm/src/api/quote.rs
  crates/bcr-ebill-wasm/src/data/mod.rs
  crates/bcr-ebill-wasm/src/error.rs
  crates/bcr-ebill-wasm/src/lib.rs
  crates/bcr-ebill-web/Cargo.toml
  crates/bcr-ebill-web/src/data.rs
  crates/bcr-ebill-web/src/handlers/bill.rs
  crates/bcr-ebill-web/src/handlers/company.rs
  crates/bcr-ebill-web/src/handlers/contacts.rs
  crates/bcr-ebill-web/src/handlers/identity.rs
  crates/bcr-ebill-web/src/handlers/mod.rs
  crates/bcr-ebill-web/src/handlers/quotes.rs
  docs/wasm.md
Labels: Review effort 3/5

#456 Minor Nostr consumer enhancements
  crates/bcr-ebill-api/Cargo.toml
  crates/bcr-ebill-api/src/service/notification_service/nostr.rs
  crates/bcr-ebill-persistence/src/constants.rs
  crates/bcr-ebill-persistence/src/db/nostr_event_offset.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_handler.rs
  crates/bcr-ebill-wasm/Cargo.toml
  crates/bcr-ebill-wasm/src/lib.rs
Labels: Review effort 2/5
