Repository BitcreditProtocol/Bitcredit-Core, pull requests merged in 2025-09, with the labels that each got.

#611 Update wasm toolchain after rustwasm archiving
  .github/workflows/rust.yml
  .github/workflows/wasm_release.yml
  CHANGELOG.md
  docs/wasm.md
Labels: Review effort 2/5, Possible security concern

#620 Refetch Bill chains
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/service.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_processor.rs
  crates/bcr-ebill-transport/src/handler/bill_invite_handler.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
  crates/bcr-ebill-transport/src/lib.rs
  crates/bcr-ebill-transport/src/notification_service.rs
  crates/bcr-ebill-transport/src/test_utils.rs
  crates/bcr-ebill-wasm/index.html
  crates/bcr-ebill-wasm/main.js
  crates/bcr-ebill-wasm/src/api/bill.rs
  crates/bcr-ebill-wasm/src/context.rs
  crates/bcr-ebill-wasm/src/data/bill.rs
Labels: Review effort 4/5, Possible security concern

#622 Identity Proof Checking API
  .github/workflows/test.yml
  CHANGELOG.md
  Cargo.toml
  crates/bcr-ebill-api/src/external/identity_proof.rs
  crates/bcr-ebill-api/src/external/mod.rs
Labels: Review effort 3/5

#626 Identity Proof Basic Implementation
  CHANGELOG.md
  crates/bcr-ebill-api/src/data/mod.rs
  crates/bcr-ebill-api/src/external/identity_proof.rs
  crates/bcr-ebill-api/src/persistence/mod.rs
  crates/bcr-ebill-api/src/service/identity_proof_service.rs
  crates/bcr-ebill-api/src/service/mod.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-core/src/identity_proof.rs
  crates/bcr-ebill-core/src/lib.rs
  crates/bcr-ebill-persistence/src/constants.rs
  crates/bcr-ebill-persistence/src/db/identity_proof.rs
  crates/bcr-ebill-persistence/src/db/mod.rs
  crates/bcr-ebill-persistence/src/identity_proof.rs
  crates/bcr-ebill-persistence/src/lib.rs
  crates/bcr-ebill-wasm/index.html
  crates/bcr-ebill-wasm/main.js
  crates/bcr-ebill-wasm/src/api/identity_proof.rs
  crates/bcr-ebill-wasm/src/api/mod.rs
  crates/bcr-ebill-wasm/src/context.rs
  crates/bcr-ebill-wasm/src/data/identity_proof.rs
  crates/bcr-ebill-wasm/src/data/mod.rs
  crates/bcr-ebill-wasm/src/error.rs
Labels: Review effort 4/5

#644 Fix unpublished blocks for reject events
  crates/bcr-ebill-transport/src/notification_service.rs
Labels: Review effort 2/5

#646 Add last_block_time to light bills endpoint
  CHANGELOG.md
  Cargo.toml
  crates/bcr-ebill-core/src/bill/mod.rs
  crates/bcr-ebill-wasm/src/data/bill.rs
Labels: Review effort 2/5

#643 Use Proxy for Identity Proof URL Checks
  CHANGELOG.md
  Cargo.toml
  crates/bcr-ebill-api/src/external/identity_proof.rs
  crates/bcr-ebill-api/src/service/identity_proof_service.rs
  crates/bcr-ebill-wasm/src/api/identity_proof.rs
Labels: Review effort 3/5, Possible security concern

#652 Add job to check identity proofs
  crates/bcr-ebill-api/src/service/identity_proof_service.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-core/src/notification.rs
  crates/bcr-ebill-persistence/src/db/identity_proof.rs
  crates/bcr-ebill-persistence/src/identity_proof.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
  crates/bcr-ebill-wasm/src/job.rs
Labels: Review effort 3/5

#658 Implement Sharing a Bill with a Court
  CHANGELOG.md
  crates/bcr-ebill-api/src/external/court.rs
  crates/bcr-ebill-api/src/external/mod.rs
  crates/bcr-ebill-api/src/lib.rs
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/bill_service/test_utils.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-transport/src/test_utils.rs
  crates/bcr-ebill-wasm/index.html
  crates/bcr-ebill-wasm/main.js
  crates/bcr-ebill-wasm/src/api/bill.rs
  crates/bcr-ebill-wasm/src/context.rs
  crates/bcr-ebill-wasm/src/data/bill.rs
  crates/bcr-ebill-wasm/src/lib.rs
Labels: Review effort 3/5, Possible security concern

#661 Remove authorized signers
  CHANGELOG.md
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/identity_service.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-core/src/bill/validation.rs
  crates/bcr-ebill-core/src/contact/mod.rs
  crates/bcr-ebill-core/src/identity/validation.rs
  crates/bcr-ebill-core/src/lib.rs
  crates/bcr-ebill-wasm/main.js
  crates/bcr-ebill-wasm/src/api/bill.rs
  crates/bcr-ebill-wasm/src/error.rs
Labels: Review effort 3/5
