Repository BitcreditProtocol/Bitcredit-Core, pull requests merged in 2025-06, with the labels that each got.

#539 fix bill cache for multiple identities
  CHANGELOG.md
  crates/bcr-ebill-api/src/service/bill_service/data_fetching.rs
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/bill_service/test_utils.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-persistence/src/bill.rs
  crates/bcr-ebill-persistence/src/constants.rs
  crates/bcr-ebill-persistence/src/db/bill.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
Labels: Review effort 2/5

#538 Chain invite handler
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/nostr.rs
  crates/bcr-ebill-core/src/blockchain/mod.rs
  crates/bcr-ebill-core/src/constants.rs
  crates/bcr-ebill-transport/src/event/bill_events.rs
  crates/bcr-ebill-transport/src/event/mod.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_handler.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_processor.rs
  crates/bcr-ebill-transport/src/handler/bill_invite_handler.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
  crates/bcr-ebill-transport/src/handler/public_bill_chain_event_handler.rs
  crates/bcr-ebill-transport/src/transport.rs
  crates/bcr-ebill-wasm/src/context.rs
Labels: Review effort 4/5

#541 upload files for mint
  crates/bcr-ebill-api/Cargo.toml
  crates/bcr-ebill-api/src/external/file_storage.rs
  crates/bcr-ebill-api/src/external/mint.rs
  crates/bcr-ebill-api/src/service/bill_service/issue.rs
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-wasm/main.js
Labels: Review effort 3/5

#545 set network to identity and check for network on startup
  CHANGELOG.md
  Cargo.toml
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-persistence/Cargo.toml
  crates/bcr-ebill-persistence/src/db/identity.rs
  crates/bcr-ebill-persistence/src/identity.rs
  crates/bcr-ebill-persistence/src/lib.rs
  crates/bcr-ebill-wasm/src/lib.rs
Labels: Review effort 3/5

#544 Use npub as id, fix sending to nostr only contact
  CHANGELOG.md
  crates/bcr-ebill-api/src/service/contact_service.rs
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/nostr.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-core/src/nostr_contact.rs
  crates/bcr-ebill-core/src/util/crypto.rs
  crates/bcr-ebill-persistence/src/db/mod.rs
  crates/bcr-ebill-persistence/src/db/nostr_contact_store.rs
  crates/bcr-ebill-persistence/src/nostr.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_processor.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
Labels: Review effort 4/5

#551 Add default mint to nostr contacts on startup
  CHANGELOG.md
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_processor.rs
  crates/bcr-ebill-wasm/main.js
Labels: Review effort 3/5

#550 407 - Add node id type, Add bill id type
  .github/workflows/rust.yml
  .github/workflows/test.yml
  CHANGELOG.md
  crates/bcr-ebill-api/Cargo.toml
  crates/bcr-ebill-core/src/bill/mod.rs
  crates/bcr-ebill-core/src/lib.rs
  crates/bcr-ebill-core/src/tests/mod.rs
  crates/bcr-ebill-persistence/src/db/bill.rs
  crates/bcr-ebill-wasm/main.js
  crates/bcr-ebill-wasm/src/error.rs
Labels: Review effort 4/5

#552 407 remove nodeid trait
  CHANGELOG.md
  Cargo.toml
  crates/bcr-ebill-api/src/service/bill_service/blocks.rs
  crates/bcr-ebill-api/src/service/bill_service/data_fetching.rs
  crates/bcr-ebill-api/src/service/bill_service/issue.rs
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/payment.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/nostr.rs
  crates/bcr-ebill-core/src/bill/mod.rs
  crates/bcr-ebill-core/src/bill/validation.rs
  crates/bcr-ebill-core/src/blockchain/bill/block.rs
  crates/bcr-ebill-core/src/blockchain/bill/chain.rs
  crates/bcr-ebill-core/src/contact/mod.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_processor.rs
Labels: Review effort 2/5

#555 Remove unnecessary borsh derives
  crates/bcr-ebill-core/src/bill/mod.rs
  crates/bcr-ebill-core/src/blockchain/bill/block.rs
  crates/bcr-ebill-core/src/blockchain/bill/chain.rs
  crates/bcr-ebill-core/src/company.rs
  crates/bcr-ebill-core/src/contact/mod.rs
  crates/bcr-ebill-core/src/identity/mod.rs
  crates/bcr-ebill-core/src/util/crypto.rs
  crates/bcr-ebill-persistence/src/bill.rs
  crates/bcr-ebill-persistence/src/company.rs
Labels: Review effort 2/5

#554 Chain event handling
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/nostr.rs
  crates/bcr-ebill-api/src/service/notification_service/test_utils.rs
  crates/bcr-ebill-transport/src/event/bill_blockchain_event.rs
  crates/bcr-ebill-transport/src/event/bill_events.rs
  crates/bcr-ebill-transport/src/handler/bill_action_event_handler.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_handler.rs
  crates/bcr-ebill-transport/src/handler/bill_invite_handler.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
  crates/bcr-ebill-transport/src/handler/public_bill_chain_event_handler.rs
  crates/bcr-ebill-transport/src/transport.rs
Labels: Review effort 4/5

#558 Add validity checks for incoming node and bill ids
  crates/bcr-ebill-api/src/data/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/blocks.rs
  crates/bcr-ebill-api/src/service/bill_service/issue.rs
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/bill_service/test_utils.rs
  crates/bcr-ebill-api/src/service/company_service.rs
  crates/bcr-ebill-api/src/service/contact_service.rs
  crates/bcr-ebill-api/src/service/identity_service.rs
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/nostr.rs
  crates/bcr-ebill-api/src/service/search_service.rs
  crates/bcr-ebill-transport/Cargo.toml
  crates/bcr-ebill-transport/src/handler/bill_chain_event_processor.rs
  crates/bcr-ebill-wasm/src/lib.rs
Labels: Review effort 4/5

#559 Switch to bitcrb token
  CHANGELOG.md
  crates/bcr-ebill-api/Cargo.toml
  crates/bcr-ebill-api/src/constants.rs
  crates/bcr-ebill-api/src/external/mint.rs
  crates/bcr-ebill-core/src/mint/mod.rs
  crates/bcr-ebill-wasm/main.js
Labels: Review effort 3/5

#563 Add plaintext hash to block data model
  CHANGELOG.md
  Cargo.toml
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-core/src/blockchain/bill/block.rs
  crates/bcr-ebill-core/src/blockchain/bill/chain.rs
  crates/bcr-ebill-core/src/blockchain/company/mod.rs
  crates/bcr-ebill-core/src/blockchain/identity/mod.rs
  crates/bcr-ebill-core/src/blockchain/mod.rs
  crates/bcr-ebill-persistence/src/constants.rs
  crates/bcr-ebill-persistence/src/db/bill_chain.rs
  crates/bcr-ebill-persistence/src/db/company_chain.rs
  crates/bcr-ebill-persistence/src/db/identity_chain.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_processor.rs
Labels: Review effort 4/5

#565 Switch to new chain transport
  crates/bcr-ebill-api/src/external/bitcoin.rs
  crates/bcr-ebill-api/src/external/mint.rs
  crates/bcr-ebill-api/src/service/notification_service/default_service.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-core/src/lib.rs
  crates/bcr-ebill-core/src/notification.rs
  crates/bcr-ebill-persistence/src/db/backup.rs
  crates/bcr-ebill-persistence/src/db/bill.rs
  crates/bcr-ebill-persistence/src/db/bill_chain.rs
  crates/bcr-ebill-persistence/src/db/company_chain.rs
  crates/bcr-ebill-persistence/src/db/identity_chain.rs
  crates/bcr-ebill-persistence/src/db/nostr_chain_event.rs
  crates/bcr-ebill-persistence/src/file_upload.rs
  crates/bcr-ebill-persistence/src/lib.rs
  crates/bcr-ebill-persistence/src/nostr.rs
  crates/bcr-ebill-persistence/src/notification.rs
  crates/bcr-ebill-transport/src/email/email_sendgrid.rs
  crates/bcr-ebill-transport/src/event/bill_events.rs
  crates/bcr-ebill-transport/src/handler/bill_action_event_handler.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_handler.rs
  crates/bcr-ebill-transport/src/handler/bill_chain_event_processor.rs
  crates/bcr-ebill-transport/src/handler/bill_invite_handler.rs
  crates/bcr-ebill-transport/src/handler/mod.rs
  crates/bcr-ebill-transport/src/lib.rs
  crates/bcr-ebill-transport/src/push_notification.rs
  crates/bcr-ebill-wasm/build.rs
  crates/bcr-ebill-wasm/src/lib.rs
Labels: Review effort 4/5, Possible security concern
