Repository BitcreditProtocol/Bitcredit-Core, pull requests merged in 2025-02, with the labels that each got.

#366 chore(docker): Optimize cache usage in build
  Dockerfile
Labels: enhancement

#419 remove cargo.lock, relax requirement on uuid version
  .gitignore
  Cargo.lock
  Cargo.toml
Labels: bug, Review effort 1/5

#420 Restructure Bills
  crates/bcr-ebill-api/Cargo.toml
  crates/bcr-ebill-api/src/dht/client.rs
  crates/bcr-ebill-api/src/service/bill_service.rs
  crates/bcr-ebill-api/src/service/bill_service/blocks.rs
  crates/bcr-ebill-api/src/service/bill_service/data_fetching.rs
  crates/bcr-ebill-api/src/service/bill_service/error.rs
  crates/bcr-ebill-api/src/service/bill_service/issue.rs
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/payment.rs
  crates/bcr-ebill-api/src/service/bill_service/propagation.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/bill_service/test_utils.rs
  crates/bcr-ebill-api/src/service/bill_service/validation.rs
  crates/bcr-ebill-api/src/service/mod.rs
  crates/bcr-ebill-core/src/bill.rs
  crates/bcr-ebill-web/src/handlers/bill.rs
  crates/bcr-ebill-web/src/handlers/mod.rs
  crates/bcr-ebill-web/src/requests/contacts.http
  docker-compose.yml
Labels: Review effort 4/5

#423 remove dht and libp2p and lettre and replace with nostr todos in prep for WASM
  Cargo.toml
  Dockerfile
  README.md
  crates/bcr-ebill-api/Cargo.toml
  crates/bcr-ebill-api/src/constants.rs
  crates/bcr-ebill-api/src/dht/behaviour.rs
  crates/bcr-ebill-api/src/dht/client.rs
  crates/bcr-ebill-api/src/dht/event_loop.rs
  crates/bcr-ebill-api/src/dht/mod.rs
  crates/bcr-ebill-api/src/lib.rs
  crates/bcr-ebill-api/src/service/bill_service/data_fetching.rs
  crates/bcr-ebill-api/src/service/bill_service/error.rs
  crates/bcr-ebill-api/src/service/bill_service/issue.rs
  crates/bcr-ebill-api/src/service/bill_service/mod.rs
  crates/bcr-ebill-api/src/service/bill_service/payment.rs
  crates/bcr-ebill-api/src/service/bill_service/propagation.rs
  crates/bcr-ebill-api/src/service/bill_service/service.rs
  crates/bcr-ebill-api/src/service/bill_service/test_utils.rs
  crates/bcr-ebill-api/src/service/bill_service/validation.rs
  crates/bcr-ebill-api/src/service/company_service.rs
  crates/bcr-ebill-api/src/service/contact_service.rs
  crates/bcr-ebill-api/src/service/identity_service.rs
  crates/bcr-ebill-api/src/service/mod.rs
  crates/bcr-ebill-api/src/service/notification_service/email_lettre.rs
  crates/bcr-ebill-api/src/service/notification_service/mod.rs
  crates/bcr-ebill-api/src/tests/mod.rs
  crates/bcr-ebill-api/src/util/mod.rs
  crates/bcr-ebill-api/src/util/terminal.rs
  crates/bcr-ebill-core/Cargo.toml
  crates/bcr-ebill-core/src/util/crypto.rs
  crates/bcr-ebill-persistence/src/db/identity.rs
  crates/bcr-ebill-persistence/src/identity.rs
  crates/bcr-ebill-web/src/config.rs
  crates/bcr-ebill-web/src/constants.rs
  crates/bcr-ebill-web/src/handlers/bill.rs
  crates/bcr-ebill-web/src/handlers/company.rs
  crates/bcr-ebill-web/src/handlers/mod.rs
  crates/bcr-ebill-web/src/main.rs
  crates/bcr-ebill-web/src/router.rs
  docker-compose.yml
  docs/configuration.md
Labels: Review effort 4/5
